---
abstract: 'L<App::Nopaste> interface to L<http://np.zakx.de>'
author:
  - 'Benjamin Stier <ben@unpatched.de>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.131560'
license: unrestricted
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-Nopaste-Service-zakx
requires:
  App::Nopaste::Service: 0
  Encode: 0
  base: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/apoxa/App-Nopaste-Service-zakx/issues
  repository: git://github.com/apoxa/App-Nopaste-Service-zakx.git
version: 0.001
